repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check src
        language: system
        pass_filenames: false
      - id: pyright
        name: pyright
        entry: uv run pyright src
        language: system
        pass_filenames: false